version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always


  backend:
    image: sofiyapalko/foodgram_backend
    env_file: ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    restart: always
    depends_on:
      - db

  frontend:
    image: sofiyapalko/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 8080:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always
